### PR TITLE
Partial fix for #599 add -remoting option

### LINKED ISSUE #599: Add Jenkins 2.54 new cli options: -http, -ssh, -remoting  to jenkins_script resource
### Cookbook version

4.2.1

### Chef-client version

Chef Development Kit Version: 1.2.22
chef-client version: 12.18.31
delivery version: master (0b746cafed65a9ea1a79de3cc546e7922de9187c)
berks version: 5.6.1
kitchen version: 1.15.0

### Platform Details

workstation - OS-X 10.12.4
target - Ubuntu 16.04 on EC2

### Scenario:
I would like to execute my groovy scripts on Jenkins 2.54 as before. So, want to add the '-remoting' flag to the jenkins_script resource.

### Steps to Reproduce:

Running jenkins_script resource

### Actual Result:

Works like a charm for Jenkins 2.53 and bellow
Works for Jenkins 2.54 when executing manually with the '-remoting' flag.
For Jenkins 2.54 with jenkins_script resource:

ec2-54-76-216-204.eu-west-1.compute.amazonaws.com [0m    ---- Begin output of "java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8080 groovy /tmp/groovy20170414-1437-11rb2yt ----
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com [0m    STDOUT: 
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com [0m    STDERR: ERROR: This command is requesting the deprecated -remoting mode. See https://jenkins.io/redirect/cli-command-requires-channel
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com [0m    ---- End output of "java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8080 groovy /tmp/groovy20170414-1437-11rb2yt ----
ec2-54-76-216-204.eu-west-1.compute.amazonaws.com [0m    Ran "java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8080 groovy /tmp/groovy20170414-1437-11rb2yt returned 5[0m

### PR DESCRIPTION
**Pull request by daften**
### Description

This is a change that allows a -remoting option to be used with jenkins-cli. Full credits go to @p0d0l

### Issues Resolved

#599 and #602 

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ X] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by daften** [comment]
Opened this PR based on the commit by @p0d0l mentioned in #599  (p0d0l/jenkins@d18f599)

File: libraries/_executor.rb [hunk 1]
```diff
@@ -73,6 +73,8 @@ def execute!(*pieces)
       command << options[:jvm_options].to_s if options[:jvm_options]
       command << %(-jar "#{options[:cli]}")
       command << %(-s #{URI.escape(options[:endpoint])}) if options[:endpoint]
+      command << %(-"#{options[:protocol]}")            if options[:protocol]
```
Comment (Dispader) [inline libraries/_executor.rb]: We might want to line up the spacing for the new lines, here.

**Comment by ehaselwanter** [comment]
@tas50 can you have a look at this?

**Comment by arothian** [comment]
For what it's worth, testing this branch against 2.46.2 fixed errors with `jenkins_plugin` for me.

**Comment by jmather** [comment]
Agreed that this changeset fixes the issues.

**Comment by tknerr** [comment]
It seems that in current versions of Jenkins 2 (tested with 2.60.1) the default `-remoting` option does not work anymore, because remoting is turned off by default.:
https://jenkins.io/doc/book/managing/cli/#remoting-connection-mode

You have to explicitly enable remoting under "Manage Jenkins -> Security" or create `/var/lib/jenkins/jenkins.CLI.xml` with the following content:
```
    <jenkins.CLI>
      <enabled>true</enabled>
    </jenkins.CLI>
```

Thanks @darioabashton who led me to this here:
https://stackoverflow.com/a/43891559/2388971
